----------------------------
--         USUARIO       --
--   DEIVITE - 22/09/20   --
----------------------------
PRINT 'Tabela: USUARIO...'

IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE object_id = OBJECT_ID('USUARIOS'))
BEGIN
   CREATE TABLE USUARIO (
          CODIGOUSUARIO						NUMERIC(10) NOT NULL,
          CODIGOINSTITUICAOENSINO			NUMERIC(10) NULL,
          NOMEUSUARIO						VARCHAR(100) NOT NULL,
          ENDERECOUSUARIO					VARCHAR(100) NULL,
          CPFUSUARIO						VARCHAR(14) NOT NULL,
          TELEFONEUSUARIO					VARCHAR(16) NULL,
          EMAILUSUARIO						VARCHAR(100) NULL,
          ATIVOUSUARIO						NUMERIC(1) NULL
   );
   ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_PK PRIMARY KEY (CODIGOUSUARIO);  
END
GO

----------------------------
--   INSTITUICAOENSINO    --
--   DEIVITE - 22/09/20   --
----------------------------
PRINT 'Tabela: INSTITUICAOENSINO...'

IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE object_id = OBJECT_ID('INSTITUICAOENSINO'))
BEGIN
   CREATE TABLE INSTITUICAOENSINO (
          CODIGOINSTITUICAOENSINO			NUMERIC(10) NOT NULL,
          NOMEINSTITUICAOENSINO				VARCHAR(100) NOT NULL,
          ENDERECOINSTITUICAOENSINO			VARCHAR(100) NOT NULL,
          CNPJINSTITUICAOENSINO				VARCHAR(14) NOT NULL,
          TELEFONEINSTITUICAOENSINO			VARCHAR(16) NOT NULL,
          ATIVOINSTITUICAOENSINO			NUMERIC(1) NULL
   );
   ALTER TABLE INSTITUICAOENSINO ADD CONSTRAINT INSTITUICAOENSINO_PK PRIMARY KEY (CODIGOINSTITUICAOENSINO);  
END
GO

----------------------------
--          LIVRO         --
--   DEIVITE - 22/09/20   --
----------------------------
PRINT 'Tabela: LIVRO...'

IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE object_id = OBJECT_ID('LIVRO'))
BEGIN
   CREATE TABLE LIVRO (
          CODIGOLIVRO						NUMERIC(10) NOT NULL,
          TITULOLIVRO						VARCHAR(100) NOT NULL,
          AUTORLIVRO						VARCHAR(100) NOT NULL,
          SINOPSELIVRO						VARCHAR(300) NOT NULL,
          CAPALIVRO							VARCHAR(16) NOT NULL,
          ATIVOLIVRO						NUMERIC(1) NULL
   );
   ALTER TABLE LIVRO ADD CONSTRAINT LIVRO_PK PRIMARY KEY (CODIGOLIVRO);  
END
GO

----------------------------
--       EMPRESTIMO       --
--   DEIVITE - 22/09/20   --
----------------------------
PRINT 'Tabela: EMPRESTIMO...'

IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE object_id = OBJECT_ID('EMPRESTIMO'))
BEGIN
   CREATE TABLE EMPRESTIMO (
          CODIGOEMPRESTIMO					NUMERIC(10) NOT NULL,
          CODIGOUSUARIO						NUMERIC(10) NOT NULL,
          CODIGOLIVRO						NUMERIC(10) NOT NULL,
          DATAEMPRESTIMO					DATETIME NOT NULL,
          DEVOLVIDOEMPRESTIMO				NUMERIC(1) NULL,
   );
   ALTER TABLE EMPRESTIMO ADD CONSTRAINT EMPRESTIMO_PK PRIMARY KEY (CODIGOEMPRESTIMO);  
END
GO

----------------------------
--       RESERVA       --
--   DEIVITE - 22/09/20   --
----------------------------
PRINT 'Tabela: RESERVA...'

IF NOT EXISTS (SELECT 1 FROM SYS.TABLES WHERE object_id = OBJECT_ID('RESERVA'))
BEGIN
   CREATE TABLE RESERVA (
          CODIGORESERVA						NUMERIC(10) NOT NULL,
          CODIGOEMPRESTIMO					NUMERICr(10) NOT NULL,
          ATIVORESERVA						NUMERIC(1) NULL,
   );
   ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_PK PRIMARY KEY (CODIGORESERVA);  
END
GO